######################################################################
# Automatically generated by qmake (3.0) Fri Jun 20 19:18:11 2014
######################################################################

TEMPLATE = app
TARGET = asciiweights
INCLUDEPATH += .

# Input
SOURCES += main.cpp
